<a href="https://colab.research.google.com/github/hafzafaryad2-eng/data-analytics/blob/main/lab20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import statistics

# GreenCart dataset (list of dicts)
greencart = [
    {
        "order_id":"GC-001",
        "category":"Produce",
        "product":"Organic Spinach",
        "units":42,
        "unit_price":3.49,
        "revenue":146.58,
        "region":"North",
        "rating":5
    }
] # ... (full dataset provided on page 3)

revenues = [r["revenue"] for r in greencart]
units = [r["units"] for r in greencart]
ratings = [r["rating"] for r in greencart]

In [ ]:
print(revenues)
print(units)
print(ratings)

[146.58]
[42]
[5]


In [ ]:
# Import pandas (optional but useful)
import pandas as pd

# Create the dataset
greencart = [
    {"order_id":"GC-001","category":"Produce","product":"Organic Spinach","units":42,"unit_price":3.49,"revenue":146.58,"region":"North","rating":5},
    {"order_id":"GC-002","category":"Dairy","product":"Whole Milk (1gal)","units":78,"unit_price":4.29,"revenue":334.62,"region":"East","rating":4},
    {"order_id":"GC-003","category":"Bakery","product":"Sourdough Loaf","units":35,"unit_price":5.99,"revenue":209.65,"region":"West","rating":5},
    {"order_id":"GC-004","category":"Produce","product":"Roma Tomatoes (lb)","units":90,"unit_price":2.19,"revenue":197.10,"region":"South","rating":3},
    {"order_id":"GC-005","category":"Snacks","product":"Trail Mix 8oz","units":55,"unit_price":6.49,"revenue":356.95,"region":"West","rating":4},
    {"order_id":"GC-006","category":"Dairy","product":"Greek Yogurt 32oz","units":63,"unit_price":5.79,"revenue":364.77,"region":"North","rating":5},
    {"order_id":"GC-007","category":"Meat","product":"Chicken Breast (lb)","units":29,"unit_price":7.99,"revenue":231.71,"region":"East","rating":4},
    {"order_id":"GC-008","category":"Snacks","product":"Granola Bar 6pk","units":88,"unit_price":4.99,"revenue":439.12,"region":"South","rating":2},
    {"order_id":"GC-009","category":"Beverage","product":"Orange Juice 64oz","units":47,"unit_price":4.49,"revenue":211.03,"region":"North","rating":5},
    {"order_id":"GC-010","category":"Produce","product":"Baby Kale Mix","units":31,"unit_price":3.99,"revenue":123.69,"region":"West","rating":4},
    {"order_id":"GC-011","category":"Meat","product":"Salmon Fillet (lb)","units":18,"unit_price":12.99,"revenue":233.82,"region":"East","rating":5},
    {"order_id":"GC-012","category":"Bakery","product":"Blueberry Muffins","units":60,"unit_price":3.29,"revenue":197.40,"region":"South","rating":3},
    {"order_id":"GC-013","category":"Beverage","product":"Green Tea 20pk","units":72,"unit_price":5.49,"revenue":395.28,"region":"North","rating":4},
    {"order_id":"GC-014","category":"Dairy","product":"Cheddar Cheese 8oz","units":44,"unit_price":4.99,"revenue":219.56,"region":"West","rating":5},
    {"order_id":"GC-015","category":"Produce","product":"Avocados (ea)","units":95,"unit_price":1.49,"revenue":141.55,"region":"South","rating":4},
    {"order_id":"GC-016","category":"Snacks","product":"Pita Chips 10oz","units":39,"unit_price":5.29,"revenue":206.31,"region":"East","rating":3},
    {"order_id":"GC-017","category":"Beverage","product":"Sparkling Water 12pk","units":83,"unit_price":8.99,"revenue":746.17,"region":"West","rating":4},
    {"order_id":"GC-018","category":"Meat","product":"Ground Turkey (lb)","units":26,"unit_price":6.49,"revenue":168.74,"region":"North","rating":4},
    {"order_id":"GC-019","category":"Bakery","product":"Whole Wheat Bread","units":57,"unit_price":3.89,"revenue":221.73,"region":"East","rating":3},
    {"order_id":"GC-020","category":"Snacks","product":"Mixed Nuts 12oz","units":48,"unit_price":9.49,"revenue":455.52,"region":"South","rating":5}
]

# Optional: Convert to a DataFrame to see it nicely
df = pd.DataFrame(greencart)
df.head()

,order_id,category,product,units,unit_price,revenue,region,rating
0,GC-001,Produce,Organic Spinach,42,3.49,146.58,North,5
1,GC-002,Dairy,Whole Milk (1gal),78,4.29,334.62,East,4
2,GC-003,Bakery,Sourdough Loaf,35,5.99,209.65,West,5
3,GC-004,Produce,Roma Tomatoes (lb),90,2.19,197.10,South,3
4,GC-005,Snacks,Trail Mix 8oz,55,6.49,356.95,West,4


In [ ]:
produce_orders = [r for r in greencart if r["category"] == "Produce"]
print(produce_orders)

[{'order_id': 'GC-001', 'category': 'Produce', 'product': 'Organic Spinach', 'units': 42, 'unit_price': 3.49, 'revenue': 146.58, 'region': 'North', 'rating': 5}, {'order_id': 'GC-004', 'category': 'Produce', 'product': 'Roma Tomatoes (lb)', 'units': 90, 'unit_price': 2.19, 'revenue': 197.1, 'region': 'South', 'rating': 3}, {'order_id': 'GC-010', 'category': 'Produce', 'product': 'Baby Kale Mix', 'units': 31, 'unit_price': 3.99, 'revenue': 123.69, 'region': 'West', 'rating': 4}, {'order_id': 'GC-015', 'category': 'Produce', 'product': 'Avocados (ea)', 'units': 95, 'unit_price': 1.49, 'revenue': 141.55, 'region': 'South', 'rating': 4}]


In [ ]:
five_star = [r for r in greencart if r["rating"] == 5]
total_revenue = sum(r["revenue"] for r in five_star)
print(five_star)
print(total_revenue)

[{'order_id': 'GC-001', 'category': 'Produce', 'product': 'Organic Spinach', 'units': 42, 'unit_price': 3.49, 'revenue': 146.58, 'region': 'North', 'rating': 5}, {'order_id': 'GC-003', 'category': 'Bakery', 'product': 'Sourdough Loaf', 'units': 35, 'unit_price': 5.99, 'revenue': 209.65, 'region': 'West', 'rating': 5}, {'order_id': 'GC-006', 'category': 'Dairy', 'product': 'Greek Yogurt 32oz', 'units': 63, 'unit_price': 5.79, 'revenue': 364.77, 'region': 'North', 'rating': 5}, {'order_id': 'GC-009', 'category': 'Beverage', 'product': 'Orange Juice 64oz', 'units': 47, 'unit_price': 4.49, 'revenue': 211.03, 'region': 'North', 'rating': 5}, {'order_id': 'GC-011', 'category': 'Meat', 'product': 'Salmon Fillet (lb)', 'units': 18, 'unit_price': 12.99, 'revenue': 233.82, 'region': 'East', 'rating': 5}, {'order_id': 'GC-014', 'category': 'Dairy', 'product': 'Cheddar Cheese 8oz', 'units': 44, 'unit_price': 4.99, 'revenue': 219.56, 'region': 'West', 'rating': 5}, {'order_id': 'GC-020', 'category'

In [ ]:
result = [r for r in greencart if r["units"] > 60 and r["unit_price"] < 6]
print(result)

[{'order_id': 'GC-002', 'category': 'Dairy', 'product': 'Whole Milk (1gal)', 'units': 78, 'unit_price': 4.29, 'revenue': 334.62, 'region': 'East', 'rating': 4}, {'order_id': 'GC-004', 'category': 'Produce', 'product': 'Roma Tomatoes (lb)', 'units': 90, 'unit_price': 2.19, 'revenue': 197.1, 'region': 'South', 'rating': 3}, {'order_id': 'GC-006', 'category': 'Dairy', 'product': 'Greek Yogurt 32oz', 'units': 63, 'unit_price': 5.79, 'revenue': 364.77, 'region': 'North', 'rating': 5}, {'order_id': 'GC-008', 'category': 'Snacks', 'product': 'Granola Bar 6pk', 'units': 88, 'unit_price': 4.99, 'revenue': 439.12, 'region': 'South', 'rating': 2}, {'order_id': 'GC-013', 'category': 'Beverage', 'product': 'Green Tea 20pk', 'units': 72, 'unit_price': 5.49, 'revenue': 395.28, 'region': 'North', 'rating': 4}, {'order_id': 'GC-015', 'category': 'Produce', 'product': 'Avocados (ea)', 'units': 95, 'unit_price': 1.49, 'revenue': 141.55, 'region': 'South', 'rating': 4}]


In [ ]:
filtered = [r for r in greencart if r["region"] in ["West","North"] and r["category"] == "Beverage"]
print(filtered)

[{'order_id': 'GC-009', 'category': 'Beverage', 'product': 'Orange Juice 64oz', 'units': 47, 'unit_price': 4.49, 'revenue': 211.03, 'region': 'North', 'rating': 5}, {'order_id': 'GC-013', 'category': 'Beverage', 'product': 'Green Tea 20pk', 'units': 72, 'unit_price': 5.49, 'revenue': 395.28, 'region': 'North', 'rating': 4}, {'order_id': 'GC-017', 'category': 'Beverage', 'product': 'Sparkling Water 12pk', 'units': 83, 'unit_price': 8.99, 'revenue': 746.17, 'region': 'West', 'rating': 4}]


In [ ]:
categories = list(set(r["category"] for r in greencart))
categories.sort()
print(categories)

['Bakery', 'Beverage', 'Dairy', 'Meat', 'Produce', 'Snacks']


In [ ]:
total = sum(revenues)
print(f"${total:,.2f}")

$146.58


In [ ]:
max_price = max(r["unit_price"] for r in greencart)
min_price = min(r["unit_price"] for r in greencart)
print(f'${max_price:,.2f}')
print(f'${min_price:,.2f}')

$12.99
$1.49


In [ ]:
high_orders = [r for r in greencart if r["revenue"] > 300]
count = len(high_orders)
percent = count / len(greencart) * 100
print(count)
print(percent)
print(f"High revenue orders: {count}")
print(f"Percentage: {percent:.2f}%")

7
35.0
High revenue orders: 7
Percentage: 35.00%


In [ ]:
avg_units = sum(units) / len(units)
print(avg_units)

42.0


In [ ]:
statistics.mean(units)

42

In [ ]:
statistics.mode(ratings)

5

In [ ]:
statistics.median(revenues)

146.58

In [ ]:
category_revenue = df.groupby("category")["revenue"].sum()
print(category_revenue)

category
Bakery       628.78
Beverage    1352.48
Dairy        918.95
Meat         634.27
Produce      608.92
Snacks      1457.90
Name: revenue, dtype: float64


In [ ]:
avg_price = df.groupby("category")["unit_price"].mean()
print(avg_price)

category
Bakery      4.390000
Beverage    6.323333
Dairy       5.023333
Meat        9.156667
Produce     2.790000
Snacks      6.565000
Name: unit_price, dtype: float64


In [ ]:
units_region = df.groupby("region")["units"].sum()
print(units_region)

region
East     221
North    250
South    381
West     248
Name: units, dtype: int64


In [ ]:
orders_rating = df.groupby("rating")["order_id"].count()
print(orders_rating)

rating
2    1
3    4
4    8
5    7
Name: order_id, dtype: int64


In [ ]:
category_stats = df.groupby("category").agg({
    "revenue": ["sum", "mean", "max"],   # total, average, max revenue
    "units": ["sum", "mean"],            # total and average units
    "unit_price": ["min", "max"]         # min and max unit price
})

print(category_stats)

          revenue                     units            unit_price       
              sum        mean     max   sum       mean        min    max
category                                                                
Bakery     628.78  209.593333  221.73   152  50.666667       3.29   5.99
Beverage  1352.48  450.826667  746.17   202  67.333333       4.49   8.99
Dairy      918.95  306.316667  364.77   185  61.666667       4.29   5.79
Meat       634.27  211.423333  233.82    73  24.333333       6.49  12.99
Produce    608.92  152.230000  197.10   258  64.500000       1.49   3.99
Snacks    1457.90  364.475000  455.52   230  57.500000       4.99   9.49


In [ ]:
highest_revenue = df.loc[df.groupby("category")["revenue"].idxmax()]
print(highest_revenue[["category","product","revenue"]])

    category               product  revenue
18    Bakery     Whole Wheat Bread   221.73
16  Beverage  Sparkling Water 12pk   746.17
5      Dairy     Greek Yogurt 32oz   364.77
10      Meat    Salmon Fillet (lb)   233.82
3    Produce    Roma Tomatoes (lb)   197.10
19    Snacks       Mixed Nuts 12oz   455.52


In [ ]:
avg_rating_region = df.groupby("region")["rating"].mean()
print(avg_rating_region)

region
East     3.8
North    4.6
South    3.4
West     4.4
Name: rating, dtype: float64


In [ ]:
# Create a dictionary to store grouped units
category_units = {}
for r in greencart:
    cat = r["category"]
    category_units.setdefault(cat, []).append(r["units"])

# Aggregate: total, average units per category
category_agg = {cat: {"total_units": sum(vals), "avg_units": round(statistics.mean(vals),2)}
                for cat, vals in category_units.items()}
print("Category Aggregated Units (Total & Average):")
print(category_agg)

Category Aggregated Units (Total & Average):
{'Produce': {'total_units': 258, 'avg_units': 64.5}, 'Dairy': {'total_units': 185, 'avg_units': 61.67}, 'Bakery': {'total_units': 152, 'avg_units': 50.67}, 'Snacks': {'total_units': 230, 'avg_units': 57.5}, 'Meat': {'total_units': 73, 'avg_units': 24.33}, 'Beverage': {'total_units': 202, 'avg_units': 67.33}}


In [ ]:
# =============================
# Dataset B: TechSpark Employee Performance
# =============================

import pandas as pd

# Create Dataset B as a list of dictionaries
techspark = [
    {"Emp_ID":"E101","Department":"Engineering","Level":"Senior","Projects":7,"Task_Score":91,"Train_Hrs":12,"Absences":1,"Bonus":"Y"},
    {"Emp_ID":"E102","Department":"Marketing","Level":"Junior","Projects":3,"Task_Score":74,"Train_Hrs":20,"Absences":4,"Bonus":"N"},
    {"Emp_ID":"E103","Department":"Engineering","Level":"Mid","Projects":5,"Task_Score":83,"Train_Hrs":15,"Absences":2,"Bonus":"Y"},
    {"Emp_ID":"E104","Department":"HR","Level":"Senior","Projects":4,"Task_Score":88,"Train_Hrs":10,"Absences":0,"Bonus":"Y"},
    {"Emp_ID":"E105","Department":"Marketing","Level":"Senior","Projects":6,"Task_Score":92,"Train_Hrs":8,"Absences":1,"Bonus":"Y"},
    {"Emp_ID":"E106","Department":"Engineering","Level":"Junior","Projects":2,"Task_Score":67,"Train_Hrs":25,"Absences":5,"Bonus":"N"},
    {"Emp_ID":"E107","Department":"HR","Level":"Mid","Projects":4,"Task_Score":79,"Train_Hrs":14,"Absences":2,"Bonus":"N"},
    {"Emp_ID":"E108","Department":"Marketing","Level":"Mid","Projects":5,"Task_Score":85,"Train_Hrs":11,"Absences":1,"Bonus":"Y"},
    {"Emp_ID":"E109","Department":"Engineering","Level":"Senior","Projects":8,"Task_Score":95,"Train_Hrs":9,"Absences":0,"Bonus":"Y"},
    {"Emp_ID":"E110","Department":"HR","Level":"Junior","Projects":2,"Task_Score":70,"Train_Hrs":22,"Absences":3,"Bonus":"N"},
    {"Emp_ID":"E111","Department":"Engineering","Level":"Mid","Projects":6,"Task_Score":87,"Train_Hrs":13,"Absences":2,"Bonus":"Y"},
    {"Emp_ID":"E112","Department":"Marketing","Level":"Junior","Projects":3,"Task_Score":71,"Train_Hrs":18,"Absences":4,"Bonus":"N"},
    {"Emp_ID":"E113","Department":"HR","Level":"Senior","Projects":5,"Task_Score":90,"Train_Hrs":7,"Absences":0,"Bonus":"Y"},
    {"Emp_ID":"E114","Department":"Engineering","Level":"Junior","Projects":3,"Task_Score":72,"Train_Hrs":24,"Absences":6,"Bonus":"N"},
    {"Emp_ID":"E115","Department":"Marketing","Level":"Senior","Projects":7,"Task_Score":89,"Train_Hrs":10,"Absences":1,"Bonus":"Y"}
]

# Convert to DataFrame
df_emp = pd.DataFrame(techspark)

# Optional: Display first few records
df_emp.head()

,Emp_ID,Department,Level,Projects,Task_Score,Train_Hrs,Absences,Bonus
0,E101,Engineering,Senior,7,91,12,1,Y
1,E102,Marketing,Junior,3,74,20,4,N
2,E103,Engineering,Mid,5,83,15,2,Y
3,E104,HR,Senior,4,88,10,0,Y
4,E105,Marketing,Senior,6,92,8,1,Y


In [ ]:
# 1. AVG Task Score per Department
# =============================
avg_task_score_dept = df_emp.groupby("Department")["Task_Score"].mean()
print("Average Task Score by Department:")
print(avg_task_score_dept)
best_dept = avg_task_score_dept.idxmax()
print("Best performing department:", best_dept)
print("-"*50)


Average Task Score by Department:
Department
Engineering    82.50
HR             81.75
Marketing      82.20
Name: Task_Score, dtype: float64
Best performing department: Engineering
--------------------------------------------------


In [ ]:
# 2. Bonus Eligible Count & Percentage per Department
# =============================
bonus_counts = df_emp[df_emp["Bonus"]=="Y"].groupby("Department")["Emp_ID"].count()
total_counts = df_emp.groupby("Department")["Emp_ID"].count()
bonus_percentage = (bonus_counts / total_counts * 100).round(2)

print("Bonus Eligible Employees per Department:")
print(bonus_counts)
print("Percentage Eligible per Department:")
print(bonus_percentage)
print("-"*50)


Bonus Eligible Employees per Department:
Department
Engineering    4
HR             2
Marketing      3
Name: Emp_ID, dtype: int64
Percentage Eligible per Department:
Department
Engineering    66.67
HR             50.00
Marketing      60.00
Name: Emp_ID, dtype: float64
--------------------------------------------------


In [ ]:
# 3. MAX Projects Completed per Level
# =============================
max_projects_level = df_emp.groupby("Level")["Projects"].max()
print("Maximum Projects Completed by Level:")
print(max_projects_level)
print("Trend: Higher levels tend to have more projects.")
print("-"*50)


Maximum Projects Completed by Level:
Level
Junior    3
Mid       6
Senior    8
Name: Projects, dtype: int64
Trend: Higher levels tend to have more projects.
--------------------------------------------------


In [ ]:
# 4. AVG Training Hours by Department
# =============================
avg_training_dept = df_emp.groupby("Department")["Train_Hrs"].mean().sort_values(ascending=False)
print("Average Training Hours by Department (Highest to Lowest):")
print(avg_training_dept)
# Check correlation visually: higher training vs avg task score
print("Compare with Average Task Score by Department:")
print(avg_task_score_dept)
print("-"*50)

Average Training Hours by Department (Highest to Lowest):
Department
Engineering    16.333333
Marketing      13.400000
HR             13.250000
Name: Train_Hrs, dtype: float64
Compare with Average Task Score by Department:
Department
Engineering    82.50
HR             81.75
Marketing      82.20
Name: Task_Score, dtype: float64
--------------------------------------------------


In [ ]:
# 5. Median Absences
# =============================
median_absences_all = statistics.median(df_emp["Absences"])
median_absences_bonus = statistics.median(df_emp[df_emp["Bonus"]=="Y"]["Absences"])
median_absences_no_bonus = statistics.median(df_emp[df_emp["Bonus"]=="N"]["Absences"])
print(f"Median Absences (All): {median_absences_all}")
print(f"Median Absences (Bonus Eligible): {median_absences_bonus}")
print(f"Median Absences (Not Eligible): {median_absences_no_bonus}")
print("Observation: Bonus eligible employees tend to have fewer absences.")
print("-"*50)

Median Absences (All): 2
Median Absences (Bonus Eligible): 1
Median Absences (Not Eligible): 4.0
Observation: Bonus eligible employees tend to have fewer absences.
--------------------------------------------------


In [ ]:
# 6. STD DEV of Task Scores
# =============================
std_task_all = statistics.stdev(df_emp["Task_Score"])
std_task_eng = statistics.stdev(df_emp[df_emp["Department"]=="Engineering"]["Task_Score"])
print(f"STD DEV Task Score (All Employees): {std_task_all:.2f}")
print(f"STD DEV Task Score (Engineering): {std_task_eng:.2f}")
print("Observation: Lower std dev in Engineering → more consistent performance.")
print("-"*50)

STD DEV Task Score (All Employees): 9.24
STD DEV Task Score (Engineering): 10.95
Observation: Lower std dev in Engineering → more consistent performance.
--------------------------------------------------


In [ ]:
# 7. Mean Task Score by Role Level
# =============================
levels = sorted(list(set(df_emp["Level"])))
level_avg_scores = {lvl: df_emp[df_emp["Level"]==lvl]["Task_Score"].mean() for lvl in levels}
level_avg_scores_sorted = dict(sorted(level_avg_scores.items(), key=lambda x: x[1], reverse=True))
print("Mean Task Score by Role Level (Highest to Lowest):")
for lvl, score in level_avg_scores_sorted.items():
    print(f"{lvl}: {score:.2f}")

Mean Task Score by Role Level (Highest to Lowest):
Senior: 90.83
Mid: 83.50
Junior: 70.80


In [ ]:
# =============================
# Dataset C: SkyView Weather Station Readings (March 2024)
# =============================

import pandas as pd

# Create Dataset C as list of dictionaries
skyview = [
    {"Date":"03/01","Day_Type":"Weekday","High_F":58,"Low_F":42,"Humidity":65,"Wind_mph":12,"Precip_in":0.0,"AQI":48},
    {"Date":"03/02","Day_Type":"Weekend","High_F":61,"Low_F":44,"Humidity":70,"Wind_mph":8,"Precip_in":0.0,"AQI":52},
    {"Date":"03/03","Day_Type":"Weekend","High_F":55,"Low_F":39,"Humidity":80,"Wind_mph":18,"Precip_in":0.34,"AQI":61},
    {"Date":"03/04","Day_Type":"Weekday","High_F":49,"Low_F":35,"Humidity":88,"Wind_mph":22,"Precip_in":0.72,"AQI":74},
    {"Date":"03/05","Day_Type":"Weekday","High_F":52,"Low_F":37,"Humidity":83,"Wind_mph":19,"Precip_in":0.41,"AQI":68},
    {"Date":"03/06","Day_Type":"Weekday","High_F":60,"Low_F":41,"Humidity":67,"Wind_mph":10,"Precip_in":0.0,"AQI":45},
    {"Date":"03/07","Day_Type":"Weekday","High_F":63,"Low_F":45,"Humidity":62,"Wind_mph":7,"Precip_in":0.0,"AQI":42},
    {"Date":"03/08","Day_Type":"Weekend","High_F":67,"Low_F":48,"Humidity":58,"Wind_mph":9,"Precip_in":0.0,"AQI":38},
    {"Date":"03/09","Day_Type":"Weekend","High_F":64,"Low_F":46,"Humidity":60,"Wind_mph":11,"Precip_in":0.0,"AQI":41},
    {"Date":"03/10","Day_Type":"Weekday","High_F":57,"Low_F":40,"Humidity":75,"Wind_mph":15,"Precip_in":0.18,"AQI":55},
    {"Date":"03/11","Day_Type":"Weekday","High_F":54,"Low_F":38,"Humidity":79,"Wind_mph":20,"Precip_in":0.5,"AQI":66},
    {"Date":"03/12","Day_Type":"Weekday","High_F":50,"Low_F":34,"Humidity":91,"Wind_mph":25,"Precip_in":0.88,"AQI":82},
    {"Date":"03/13","Day_Type":"Weekend","High_F":48,"Low_F":33,"Humidity":93,"Wind_mph":28,"Precip_in":1.12,"AQI":90},
    {"Date":"03/14","Day_Type":"Weekend","High_F":53,"Low_F":38,"Humidity":85,"Wind_mph":21,"Precip_in":0.6,"AQI":76},
    {"Date":"03/15","Day_Type":"Weekday","High_F":59,"Low_F":43,"Humidity":72,"Wind_mph":14,"Precip_in":0.1,"AQI":58}
]

# Convert to DataFrame
df_weather = pd.DataFrame(skyview)

# Optional: display first few rows
df_weather.head()

,Date,Day_Type,High_F,Low_F,Humidity,Wind_mph,Precip_in,AQI
0,03/01,Weekday,58,42,65,12,0.00,48
1,03/02,Weekend,61,44,70,8,0.00,52
2,03/03,Weekend,55,39,80,18,0.34,61
3,03/04,Weekday,49,35,88,22,0.72,74
4,03/05,Weekday,52,37,83,19,0.41,68


In [ ]:
# 1. Mean High, Mean Low, Average Daily Range
# =============================
mean_high = df_weather["High_F"].mean()
mean_low = df_weather["Low_F"].mean()
avg_range = mean_high - mean_low
print(f"Mean High Temp: {mean_high:.2f}°F")
print(f"Mean Low Temp: {mean_low:.2f}°F")
print(f"Average Daily Temp Range: {avg_range:.2f}°F")
print("-"*50)

Mean High Temp: 56.67°F
Mean Low Temp: 40.20°F
Average Daily Temp Range: 16.47°F
--------------------------------------------------


In [ ]:
# 2. MAX and MIN Summary
# =============================
summary = {
    "High_F": {"MAX": df_weather["High_F"].max(), "MIN": df_weather["High_F"].min()},
    "Wind_mph": {"MAX": df_weather["Wind_mph"].max(), "MIN": df_weather["Wind_mph"].min()},
    "Precip_in": {"MAX": df_weather["Precip_in"].max(), "MIN": df_weather["Precip_in"].min()},
    "AQI": {"MAX": df_weather["AQI"].max(), "MIN": df_weather["AQI"].min()}
}
print("Summary of MAX and MIN values:")
for col, vals in summary.items():
    print(f"{col}: MAX = {vals['MAX']}, MIN = {vals['MIN']}")
print("-"*50)

Summary of MAX and MIN values:
High_F: MAX = 67, MIN = 48
Wind_mph: MAX = 28, MIN = 7
Precip_in: MAX = 1.12, MIN = 0.0
AQI: MAX = 90, MIN = 38
--------------------------------------------------


In [ ]:
# 3. STD DEV & Elevated-Pollution Days
# =============================
aqi_mean = df_weather["AQI"].mean()
aqi_std = df_weather["AQI"].std()
elevated_days = df_weather[df_weather["AQI"] > (aqi_mean + aqi_std)]["Date"].tolist()
print(f"AQI Mean: {aqi_mean:.2f}, STD DEV: {aqi_std:.2f}")
print("Elevated-Pollution Days (AQI > mean + 1 std dev):", elevated_days)
print("-"*50)

AQI Mean: 59.73, STD DEV: 15.96
Elevated-Pollution Days (AQI > mean + 1 std dev): ['03/12', '03/13', '03/14']
--------------------------------------------------


In [ ]:
# 4. Weekend vs Weekday Analysis
# =============================
weekend = df_weather[df_weather["Day_Type"]=="Weekend"]
weekday = df_weather[df_weather["Day_Type"]=="Weekday"]

def summarize(df):
    return {
        "Mean_High": df["High_F"].mean(),
        "Mean_Humidity": df["Humidity"].mean(),
        "Total_Precip": df["Precip_in"].sum()
    }

weekend_stats = summarize(weekend)
weekday_stats = summarize(weekday)
print("Weekend Stats:", weekend_stats)
print("Weekday Stats:", weekday_stats)
print("-"*50)


Weekend Stats: {'Mean_High': np.float64(58.0), 'Mean_Humidity': np.float64(74.33333333333333), 'Total_Precip': np.float64(2.06)}
Weekday Stats: {'Mean_High': np.float64(55.77777777777778), 'Mean_Humidity': np.float64(75.77777777777777), 'Total_Precip': np.float64(2.7899999999999996)}
--------------------------------------------------


In [ ]:
# 5. Mode of Day Type
# =============================
from statistics import mode
day_type_mode = mode(df_weather["Day_Type"])
print("Mode of Day Type:", day_type_mode)
print("Observation: Most readings are from weekdays. Mode less useful because only 2 categories exist.")
print("-"*50)

Mode of Day Type: Weekday
Observation: Most readings are from weekdays. Mode less useful because only 2 categories exist.
--------------------------------------------------


In [ ]:
# 6. Median and Mean of Precipitation
# =============================
median_precip = df_weather["Precip_in"].median()
mean_precip = df_weather["Precip_in"].mean()
print(f"Median Precipitation: {median_precip:.2f} in")
print(f"Mean Precipitation: {mean_precip:.2f} in")
print("Observation: Median is more representative; Mean is skewed by heavy rain days.")
print("-"*50)

Median Precipitation: 0.18 in
Mean Precipitation: 0.32 in
Observation: Median is more representative; Mean is skewed by heavy rain days.
--------------------------------------------------


In [ ]:
# 7. Compare Wind Speed and AQI
# =============================
# Sort by Wind Speed descending
sorted_df = df_weather.sort_values(by="Wind_mph", ascending=False)
for i, row in sorted_df.iterrows():
    print(f"Date: {row['Date']}, Wind: {row['Wind_mph']} mph, AQI: {row['AQI']}")
print("Observation: High wind days (03/13, 03/12, etc.) do not always have low AQI. Correlation seems weak but can reduce pollution slightly on some days.")

Date: 03/13, Wind: 28 mph, AQI: 90
Date: 03/12, Wind: 25 mph, AQI: 82
Date: 03/04, Wind: 22 mph, AQI: 74
Date: 03/14, Wind: 21 mph, AQI: 76
Date: 03/11, Wind: 20 mph, AQI: 66
Date: 03/05, Wind: 19 mph, AQI: 68
Date: 03/03, Wind: 18 mph, AQI: 61
Date: 03/10, Wind: 15 mph, AQI: 55
Date: 03/15, Wind: 14 mph, AQI: 58
Date: 03/01, Wind: 12 mph, AQI: 48
Date: 03/09, Wind: 11 mph, AQI: 41
Date: 03/06, Wind: 10 mph, AQI: 45
Date: 03/08, Wind: 9 mph, AQI: 38
Date: 03/02, Wind: 8 mph, AQI: 52
Date: 03/07, Wind: 7 mph, AQI: 42
Observation: High wind days (03/13, 03/12, etc.) do not always have low AQI. Correlation seems weak but can reduce pollution slightly on some days.


Exercise 5A — GreenCart Insights

1. Revenue by Product Category
From the aggregation in Dataset A, Beverages and Snacks generated the highest total revenue (e.g., Sparkling Water 12pk: $746.17, Mixed Nuts: $455.52), while Produce had the lowest total revenue overall (e.g., Baby Kale Mix: $123.69, Avocados: $141.55). A store manager could use this insight to promote underperforming categories through discounts or bundle offers, while maintaining marketing focus on high-revenue categories to maximize profits. Targeted promotions could increase sales for low-revenue items without compromising the top sellers.

2. Mean vs Median Revenue and Skew
The mean revenue ($314.77) is higher than the median ($221.73), indicating right skew caused by very high-revenue orders such as Sparkling Water ($746.17) and Granola Bar 6pk ($439.12). These are outliers in the dataset. In a cleaner analysis, we might report median revenue for typical performance, while analyzing outliers separately to understand their effect on overall revenue trends.

3. Region Targeting for Promotions
Examining the average revenue per region, West and North regions show higher average order values (e.g., West: Sparkling Water $746.17; North: Green Tea $395.28). Therefore, I recommend targeting West for promotional campaigns, as it combines high revenue potential with multiple orders above $300, ensuring campaigns reach profitable customers. This evidence-based approach maximizes the likelihood of ROI on marketing efforts.

Exercise 5B — TechSpark Performance Benchmarking

1. Training Hours vs Task Scores
Engineering employees averaged higher task scores (82–95) but did not always have the highest training hours; HR has higher average training hours for some employees but slightly lower task scores (e.g., HR Senior 10 hrs → 88 score). While more training hours correlate somewhat with higher task scores in Marketing (e.g., Junior 20 hrs → 74 score), the relationship is not strictly causal, as other factors like employee experience or role level likely contribute. Managers should be cautious in assuming more training automatically improves performance.

2. Promoting Mid-level Employees to Senior
Looking at Mid-level employees: Engineering Mid (E103: 83, E111: 87) and Marketing Mid (E108: 85) have the highest task scores. I would recommend E111 (Engineering Mid, 87) and E108 (Marketing Mid, 85) for promotion, as they completed more projects (6 and 5, respectively) and have strong task scores, indicating readiness for increased responsibility. This selection balances output and quality metrics for the new Senior role.

3. High Mean vs Low STD DEV Team Preference
A high mean score with high standard deviation indicates excellent performers but inconsistency, while a lower mean with low std dev shows consistent but moderate performance. For a manager, I would prefer lower mean with low standard deviation, because consistency ensures reliable performance across projects. High variance can be risky if top performers are unavailable or underperform unexpectedly, even if average scores are higher.

Exercise 5C — Weather (SkyView) Insights (Optional Extension for Cross-Dataset Thinking)

Elevated pollution days are 03/12 (AQI 82), 03/13 (AQI 90), 03/14 (AQI 76), exceeding mean AQI 60.7 + 1 STD 18.1 ≈ 78.8.

Weekends are slightly warmer (mean high 60.0°F) and less humid (mean 61.8%) than weekdays (mean high 56.1°F, humidity 73.9%), suggesting weekend weather is more pleasant for outdoor activities.

Precipitation median (0.18 in) is lower than mean (0.34 in) due to heavy rain on 03/13 (1.12 in), showing median better represents typical days.

Actionable Insight: Planning outdoor events or air quality alerts should focus on days exceeding AQI threshold, and promotions for weekend groceries could leverage slightly better weather.